### ISSUE TITLE
get ODE_FBA composite working with a tellurium/cobra configuration

### ISSUE THREAD

**Issue by eagmon** [vivarium-collective/vivarium-biosimulators#14]
The first step to making `ODE_FBA` into a general composite that can implement any ode simulator and fba simulator hybrid, is to test it on a particular set. I am working towards a tellurium/cobra hybrid.

The TODOs to get this working are: 
- [x] extract initial state for `cobra` and `tellurium`, use in `tellurium_cobra`
- [x] configure the `coupled_reactions` in `ODE_FBA`. `FluxBoundsConverter` will be converting these reactions from ode flux outputs to fba flux_bounds inputs.
- [ ] `BiosimulatorsProcess` needs a configurable `get_delta` equivalent, which would work for different data types.
- [x] `BiosimulatorsProcess` needs configurable default types for individual variables -- they might not all be the same. Perhaps group datatypes into different ports?
- [x] Need to add an input variable to COBRA model -- a flux bound on `EX_lac__D_e`, like there already is for `value_parameter_R_EX_glc__D_e_lower_bound`.

**Comment by jonrkarr** [comment]
`get_parameters_variables_outputs_for_simulation` returns the initial state for both FBA and continuous models.

**Comment by eagmon** [comment]
@jonrkarr -- I ended up using `exec_sed_task` to get the expected output data types, so they don't have to be user-configured. This works fine for now: https://github.com/vivarium-collective/vivarium-biosimulators/blob/ef499762a9b57a97316463e8eff2414d0ea0c550/vivarium_biosimulators/processes/biosimulator_process.py#L194-L198
